# Generated by Django 4.2.30 on 2026-09-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='booking_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ['ASSIGNED', 'ON_THE_WAY', 'ARRIVED', 'IN_PROGRESS']), _negated=True), ('mechanic__isnull', False), _connector='OR'), name='active_status_requires_mechanic'),
        ),
    ]
