# Generated by Django 4.2.30 on 2026-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='completed_requires_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='cancelled_requires_cancelled_at'),
        ),
    ]
