# Generated by Django 4.2.30 on 2026-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_completed_requires_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
