# Generated by Django 4.2.30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='version',
        ),
    ]
