# Generated by Django 4.2.30 on 2026-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mechanic',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='mechanic_rating_between_0_and_5'),
        ),
    ]
